### ISSUE TITLE
The 3D visualization did not appear for me on binder

### ISSUE THREAD

**Issue by rsignell-usgs** [davidbrochart/dem3d#3]
I tried both Opera and Chrome browers, but the 3D visualization did not appear for me on binder.   No warnings, just kept spinning...   ![2020-12-19_7-03-09](https://user-images.githubusercontent.com/1872600/102690143-5ed63900-41d1-11eb-9559-a2ba4b3ce412.jpg)

**Comment by davidbrochart** [comment]
Would be interesting to see if you have some error in the browser console. Is it on binder or installed locally? If it's on binder then it clears out any installation issue. The ultimate thing would be that you don't have an integrated GPU (ipygany needs one), but it's almost impossible these days.

**Comment by davidbrochart** [comment]
Oh, you wrote it was on binder. Maybe you got a very slow machine, or with not enough memory. Can you try reducing the size of the selection?

**Comment by rsignell-usgs** [comment]
@davidbrochart You were right!   I tried a 0.5x0.5 degree square and it worked!
